/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/architecture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Repository Architecture */
        post: operations["analyze_repository_architecture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Repository Change Impact */
        post: operations["analyze_repository_change_impact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Repository Question */
        post: operations["answer_repository_question"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Repository */
        post: operations["submit_repository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcquisitionErrorCode
         * @enum {string}
         */
        AcquisitionErrorCode: "invalid_archive" | "unsafe_archive_path" | "archive_limit_exceeded" | "invalid_source_encoding" | "invalid_source_response" | "source_unavailable";
        /**
         * AnswerStatus
         * @enum {string}
         */
        AnswerStatus: "answered" | "insufficient_evidence" | "unsupported";
        /** ApiErrorDetail */
        ApiErrorDetail: {
            /** Code */
            code: components["schemas"]["RepositoryErrorCode"] | components["schemas"]["AcquisitionErrorCode"] | "invalid_request";
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            error: components["schemas"]["ApiErrorDetail"];
        };
        /** ArchitectureLimitation */
        ArchitectureLimitation: {
            code: components["schemas"]["LimitationCode"];
            /** Line */
            line: number;
            /** Path */
            path: string;
            /** Subject */
            subject: string;
        };
        /** ArchitectureModule */
        ArchitectureModule: {
            language: components["schemas"]["SourceLanguage"];
            parse_status: components["schemas"]["ParseStatus"];
            /** Path */
            path: string;
            /** Symbols */
            symbols: components["schemas"]["ArchitectureSymbol"][];
        };
        /** ArchitectureRelationship */
        ArchitectureRelationship: {
            kind: components["schemas"]["DependencyKind"];
            /** Line */
            line: number;
            /** Local Name */
            local_name: string;
            resolution: components["schemas"]["RelationshipResolution"];
            /** Source Path */
            source_path: string;
            /** Specifier */
            specifier: string;
            /** Target Path */
            target_path: string | null;
            /** Target Symbol */
            target_symbol: string;
        };
        /** ArchitectureSymbol */
        ArchitectureSymbol: {
            kind: components["schemas"]["SymbolKind"];
            /** Line */
            line: number;
            /** Name */
            name: string;
        };
        /** ArchitectureView */
        ArchitectureView: {
            /** Limitations */
            limitations: components["schemas"]["ArchitectureLimitation"][];
            /** Modules */
            modules: components["schemas"]["ArchitectureModule"][];
            /** Relationships */
            relationships: components["schemas"]["ArchitectureRelationship"][];
            repository: components["schemas"]["RepositoryIdentity"];
            /** Revision */
            revision: string;
        };
        /** ChangeImpactReport */
        ChangeImpactReport: {
            /** Candidates */
            candidates: components["schemas"]["RetrievedEvidence"][];
            /** Impacts */
            impacts: components["schemas"]["ImpactedModule"][];
            location_confidence: components["schemas"]["ImpactConfidence"];
            /** Query */
            query: string;
            status: components["schemas"]["RetrievalStatus"];
            /** Truncated */
            truncated: boolean;
            /** Warnings */
            warnings: string[];
        };
        /** CitedAnswer */
        CitedAnswer: {
            /** Evidence */
            evidence: components["schemas"]["RetrievedEvidence"][];
            /** Facts */
            facts: components["schemas"]["CitedFact"][];
            /**
             * Inference
             * @default []
             */
            inference: string[];
            /** Query */
            query: string;
            status: components["schemas"]["AnswerStatus"];
        };
        /** CitedFact */
        CitedFact: {
            basis: components["schemas"]["EvidenceBasis"];
            /** Citations */
            citations: components["schemas"]["SourceCitation"][];
            /** Text */
            text: string;
        };
        /**
         * DependencyKind
         * @enum {string}
         */
        DependencyKind: "import" | "re_export";
        /**
         * EvidenceBasis
         * @enum {string}
         */
        EvidenceBasis: "verified_source";
        /**
         * EvidenceKind
         * @enum {string}
         */
        EvidenceKind: "module" | "relationship" | "symbol";
        /** HealthResponse */
        HealthResponse: {
            /**
             * Service
             * @constant
             */
            service: "codeatlas-analysis";
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * ImpactConfidence
         * @enum {string}
         */
        ImpactConfidence: "high" | "medium" | "low";
        /** ImpactedModule */
        ImpactedModule: {
            /** Depth */
            depth: number;
            evidence: components["schemas"]["SourceCitation"];
            /** Path */
            path: string;
        };
        /**
         * LimitationCode
         * @enum {string}
         */
        LimitationCode: "ambiguous_module" | "external_dependency" | "partial_parse" | "unresolved_module" | "unresolved_symbol";
        /**
         * ParseStatus
         * @enum {string}
         */
        ParseStatus: "complete" | "partial";
        /**
         * RelationshipResolution
         * @enum {string}
         */
        RelationshipResolution: "ambiguous" | "external" | "module_unresolved" | "resolved" | "symbol_unresolved";
        /**
         * RepositoryErrorCode
         * @enum {string}
         */
        RepositoryErrorCode: "invalid_repository_url" | "unsupported_repository_scheme" | "unsupported_repository_host" | "unsafe_repository_url" | "invalid_repository_path";
        /** RepositoryIdentity */
        RepositoryIdentity: {
            /** Canonical Url */
            canonical_url: string;
            /** Host */
            host: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Owner */
            owner: string;
        };
        /** RepositoryIdentityResponse */
        RepositoryIdentityResponse: {
            /** Canonical Url */
            canonical_url: string;
            /**
             * Host
             * @constant
             */
            host: "github.com";
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Owner */
            owner: string;
        };
        /** RepositoryIntakeRequest */
        RepositoryIntakeRequest: {
            /** Repository Url */
            repository_url: string;
        };
        /** RepositoryIntakeResponse */
        RepositoryIntakeResponse: {
            repository: components["schemas"]["RepositoryIdentityResponse"];
            status: components["schemas"]["RepositoryStatus"];
        };
        /** RepositoryQuestionRequest */
        RepositoryQuestionRequest: {
            /** Question */
            question: string;
            /** Repository Url */
            repository_url: string;
        };
        /**
         * RepositoryStatus
         * @enum {string}
         */
        RepositoryStatus: "pending" | "processing" | "ready" | "failed";
        /**
         * RetrievalMethod
         * @enum {string}
         */
        RetrievalMethod: "lexical" | "semantic";
        /**
         * RetrievalStatus
         * @enum {string}
         */
        RetrievalStatus: "found" | "insufficient_evidence";
        /** RetrievedEvidence */
        RetrievedEvidence: {
            basis: components["schemas"]["EvidenceBasis"];
            citation: components["schemas"]["SourceCitation"];
            kind: components["schemas"]["EvidenceKind"];
            /** Matched Terms */
            matched_terms: string[];
            /** @default lexical */
            method: components["schemas"]["RetrievalMethod"];
            /** Score */
            score: number;
        };
        /** SourceCitation */
        SourceCitation: {
            /** End Line */
            end_line: number;
            /** Path */
            path: string;
            /** Start Line */
            start_line: number;
            /** Symbol */
            symbol?: string | null;
        };
        /**
         * SourceLanguage
         * @enum {string}
         */
        SourceLanguage: "javascript" | "json" | "jsx" | "typescript" | "tsx";
        /**
         * SymbolKind
         * @enum {string}
         */
        SymbolKind: "class" | "enum" | "function" | "interface" | "type_alias" | "variable";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_repository_architecture: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryIntakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchitectureView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    analyze_repository_change_impact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeImpactReport"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    answer_repository_question: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CitedAnswer"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    submit_repository: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryIntakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryIntakeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
